version: '3.8'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # volumes:
      # - './backend:/app'
      # - './backend/node_modules:/app/node_modules'
    ports:
      - 5000:5000

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
      # - './frontend:/app'
      # - './frontend/node_modules:/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_URL=http://backend:5000
    depends_on:
      - backend
